name: Make tests_run

on: [push, pull_request]

jobs:
  build-check:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest

    steps:
      - uses: actions/checkout@v4
      - name: make tests_run
        run: tests_run
